export const ACCOUNT_ADDED_SUCCESS = ' ACCOUNT_ADDED_SUCCESS ';
export const ACCOUNT_ADDED_FAIL = 'ACCOUNT_ADDED_FAIL';
export const DC_ADDED_SUCCESS = 'DC_ADDED_SUCCESS';
export const DC_ADDED_FAIL = 'DC_ADDED_FAIL';
